from __future__ import annotations

from client.cli_app.app import (
    DEFAULT_BASE_URL,
    InputFn,
    OutputFn,
    _build_parser,
    _normalize_argv,
    main,
    run_cli,
)
from client.cli_app.commands import (
    normalize_rank,
    normalized_card_label,
    read_command,
    read_stdin_with_deadline,
    resolve_card_inputs,
    resolve_card_label,
    submit_human_command,
)
from client.cli_app.render import (
    SUIT_EMOJI,
    SUIT_INPUT_ALIASES,
    card_sort_key,
    client_error_code,
    format_card_id,
    format_card_list,
    format_client_error,
    format_command_response,
    format_directional_seat_summary,
    format_event,
    format_friend_mark,
    format_hand,
    format_npc_metadata,
    format_public_snapshot,
    format_seat_snapshot,
    format_seat_summary,
    format_timer,
    format_timeout_fallback,
    help_text,
    sort_card_ids,
)
from client.cli_app.session import CliSession, prepare_default_table
from client.cli_app.state_machine import (
    CliMachineState,
    CliStateMachine,
    deal_seed,
    drive_bot_turns,
    input_deadline_epoch_ms,
    refresh_after_input_timeout,
    snapshot_acting_seat,
)
from client.cli_app.types import CliResult


__all__ = [
    "DEFAULT_BASE_URL",
    "CliMachineState",
    "CliResult",
    "CliSession",
    "CliStateMachine",
    "InputFn",
    "OutputFn",
    "SUIT_EMOJI",
    "SUIT_INPUT_ALIASES",
    "_build_parser",
    "_normalize_argv",
    "card_sort_key",
    "client_error_code",
    "drive_bot_turns",
    "format_card_id",
    "format_card_list",
    "format_client_error",
    "format_command_response",
    "format_directional_seat_summary",
    "format_event",
    "format_friend_mark",
    "format_hand",
    "format_npc_metadata",
    "format_public_snapshot",
    "format_seat_snapshot",
    "format_seat_summary",
    "format_timer",
    "format_timeout_fallback",
    "help_text",
    "input_deadline_epoch_ms",
    "main",
    "normalize_rank",
    "normalized_card_label",
    "prepare_default_table",
    "read_command",
    "read_stdin_with_deadline",
    "refresh_after_input_timeout",
    "deal_seed",
    "resolve_card_inputs",
    "resolve_card_label",
    "run_cli",
    "snapshot_acting_seat",
    "sort_card_ids",
    "submit_human_command",
]


if __name__ == "__main__":
    raise SystemExit(main())
